### ISSUE TITLE
SEG FAULT when converting CMYK to RGBA

### ISSUE THREAD

**Issue by kidkidkid** [mm2/Little-CMS#268]
hi, i encounter a problem when i transform a jpeg image from CMYK to RGB. However, it works when source image is small but core dumps when image is larger. I could not figure it out totally.
Code is simple, sRGB is created using cms, in profile is read from image:
```
cmsHTRANSFORM xform = cmsCreateTransform(in, TYPE_CMYK_8, sRGB, TYPE_RGBA_8, INTENT_PERCEPTUAL, 0);
cmsDoTransform(xform, out_data, final_data, out_size);
```
However, it core dumps ad follows. Any idea about how it happens?
```
==95972==The signal is caused by a WRITE memory access. 
    #0 0x10023d5c4 in Pack3BytesAndSkip1 cmspack.c:1954
    #1 0x100243cca in CachedXFORM cmsxform.c:548
    #2 0x1002416e1 in cmsDoTransform cmsxform.c:206
````

**Comment by kidkidkid** [comment]
sorry, i find the mistake. I close the issue.
