### ISSUE TITLE
Heap-buffer-overflow in cmsAppendNamedColor ... Is this a bug?

### ISSUE THREAD

**Issue by frokaikan** [mm2/Little-CMS#317]
Here is the program
```c++
#include "lcms2.h"

int main (int argc, char **argv) {
    cmsNAMEDCOLORLIST *list = cmsAllocNamedColorList(nullptr, 31279, 4278910976, "/z", "/");
    cmsAppendNamedColor(list, "\xff/", nullptr, nullptr);
}
```
and AddressSanitizer reports like this:
```
=================================================================
==1105937==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f3c551ef800 at pc 0x7f3c5966fbd1 bp 0x7ffdce01c860 sp 0x7ffdce01c858
WRITE of size 2 at 0x7f3c551ef800 thread T0
    #0 0x7f3c5966fbd0 in cmsAppendNamedColor 
    #1 0x4c6c02 in main 
    #2 0x7f3c58fb50b2 in __libc_start_main 
    #3 0x41c40d in _start 

0x7f3c551ef800 is located 0 bytes to the right of 9633792-byte region [0x7f3c548bf800,0x7f3c551ef800)
allocated by thread T0 here:
    #0 0x494e69 in realloc 
    #1 0x7f3c595a4f87 in _cmsReallocDefaultFn 
    #2 0x7f3c595a632c in _cmsRealloc 
    #3 0x7f3c5966edbf in GrowNamedColorList 
    #4 0x7f3c5966e871 in cmsAllocNamedColorList 
    #5 0x4c6be7 in main 
    #6 0x7f3c58fb50b2 in __libc_start_main 

SUMMARY: AddressSanitizer: heap-buffer-overflow in cmsAppendNamedColor
Shadow bytes around the buggy address:
  0x0fe80aa35eb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe80aa35ec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe80aa35ed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe80aa35ee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe80aa35ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe80aa35f00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe80aa35f10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe80aa35f20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe80aa35f30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe80aa35f40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe80aa35f50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1105937==ABORTING
```

**Comment by mm2** [comment]
Calling functions with wrong parameters obviously can lead to wrong results.  printf((void*) 123); crashes and nobody thinks this is a printf bug. In the case you could force such  call by using an ICC profile, that would be a vulnerability, but actually this is just a bug on the caller side.
