### ISSUE TITLE
NULL dereference in  BuildAbsolutePath

### ISSUE THREAD

**Issue by anfedotoff** [mm2/Little-CMS#331]
Hi!
While fuzzing I could trigger this such case:
```
Starting program: /lcms_sydr/cmsIT8_load_sydr /fuzz/crash-0485db99e2b54857ef08923bcf3b1252afe03603

#0  __strncpy_avx2 () at ../sysdeps/x86_64/multiarch/strcpy-avx2.S:363
#1  0x0000000000219b19 in strncpy (__len=255, __src=0x4ae8d0 "", __dest=0x0) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:106
#2  BuildAbsolutePath (MaxLen=255, buffer=0x0, basePath=0x4ae8d0 "", relPath=0x4aee08 "") at cmscgats.c:492
#3  InSymbol (it8=it8@entry=0x46c350) at cmscgats.c:1002
#4  0x000000000021b470 in DataFormatSection (it8=0x46c350) at cmscgats.c:1965
#5  ParseIT8 (it8=it8@entry=0x46c350, nosheet=nosheet@entry=0) at cmscgats.c:2202
#6  0x000000000021bc12 in cmsIT8LoadFromMem (ContextID=0x0, Ptr=0x46c0c0, len=644) at cmscgats.c:2443
#7  0x0000000000217eea in LLVMFuzzerTestOneInput (
    data=0x46c0c0 "an:\n\tan:\n\t=rm 4esvs\tl;q\r\r\r\r\r\r\rCCAaW:\n\tan:\n\t=rm 4esvs\rl;q", '\r' <repeats 20 times>, "sucms.o ../src/li\n\t-rs\n\nins", '\032' <repeats 21 times>, "*\032\032\032\032\032\n\ninstal\\:\n BMME\"\r\nNUMBER_OF_FIELDS\t0666666566c/li\n\t-rs\n\nins\032\032\032\032\032\032\032\066ER"..., size=644) at ./cmsIT8_load_sydr.c:28
#8  0x0000000000217fcf in main (argc=2, argv=0x7fffffffe668) at ./cmsIT8_load_sydr.c:45
```
It's known  [problem](https://github.com/anfedotoff/Little-CMS/blob/master/src/cmscgats.c#L998), I think. 
I attach [crash-0485db99e2b54857ef08923bcf3b1252afe03603.txt](https://github.com/mm2/Little-CMS/files/9310152/crash-0485db99e2b54857ef08923bcf3b1252afe03603.txt).
If you interested how to reproduce, please look [here](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/lcms).

**Comment by anfedotoff** [comment]
Fixed by this [commit](https://github.com/mm2/Little-CMS/commit/a6ef58ec3716bad934d0cacc063ef1a419f4668f).
