### ISSUE TITLE
Segfault when setting sRGB profile via imagemagick

### ISSUE THREAD

**Issue by davidpersson** [mm2/Little-CMS#41]
Hi!

I have a PHP script that generates images off of PDFs (via imagick -> imagemagick -> ghostscript), it reproducibly segfaults when assigning a profile to it. I've attached a gdb stack trace. 

I hope this isn't due to some other bug elsewhere in the stack.

I'm using:
ghostscript 9.10-r2
lcms 2.6-r1 (most recent in Gentoo Portage)
imagemagick  6.9.0.3

Linux a 3.17.7-gentoo #1 SMP Mon Jan 5 13:34:45 UTC 2015 x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux

```
Core was generated by `/usr/bin/php /var/www/npiece/vendors/cake/console/cake.php -app /var/www/npiece'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f8824f8121d in _cmsMallocZeroDefaultFn (ContextID=<optimized out>, size=3752)
    at /var/tmp/portage/media-libs/lcms-2.6-r1/work/lcms2-2.6/src/cmserr.c:97
#2  0x00007f8824f87eb2 in cmsCreateProfilePlaceholder (ContextID=ContextID@entry=0x1d31420)
    at /var/tmp/portage/media-libs/lcms-2.6-r1/work/lcms2-2.6/src/cmsio0.c:460
#3  0x00007f8824f892e8 in cmsOpenProfileFromMemTHR (ContextID=ContextID@entry=0x1d31420, MemPtr=0x1cdef20, dwSize=dwSize@entry=3048)
    at /var/tmp/portage/media-libs/lcms-2.6-r1/work/lcms2-2.6/src/cmsio0.c:1118
#4  0x00007f88252e104a in ProfileImage (image=0x1d31420, name=name@entry=0x7f882cd51c50 "icc", datum=datum@entry=0x1cb8d80, length=length@entry=3048, 
    magick_unused_clone=magick_unused_clone@entry=MagickTrue) at magick/profile.c:865
#5  0x00007f88256274eb in MagickProfileImage (wand=0x1961790, name=0x7f882cd51c50 "icc", profile=0x1cb8d80, length=3048) at wand/magick-property.c:1728
#6  0x00007f88258c3bb0 in zim_imagick_profileimage (ht=<optimized out>, return_value=0x1cb3a48, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /var/tmp/portage/dev-php/pecl-imagick-3.2.0_rc1/work/php5.5/imagick_class.c:4545
#7  0x00000000008017da in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>)
    at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/Zend/zend_vm_execute.h:550
#8  0x000000000077a3d8 in execute_ex (execute_data=0x7f882cd88df8) at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/Zend/zend_vm_execute.h:363
#9  0x0000000000742e38 in zend_call_function (fci=fci@entry=0x7fffd18235e0, fci_cache=<optimized out>, fci_cache@entry=0x7fffd18235b0)
    at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/Zend/zend_execute_API.c:934
#10 0x0000000000658312 in zif_call_user_func_array (ht=<optimized out>, return_value=0x1c1d8a8, return_value_ptr=<optimized out>, this_ptr=<optimized out>, 
    return_value_used=<optimized out>) at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/ext/standard/basic_functions.c:4812
#11 0x00000000008017da in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>)
    at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/Zend/zend_vm_execute.h:550
#12 0x000000000077a3d8 in execute_ex (execute_data=0x7f882cd88518) at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/Zend/zend_vm_execute.h:363
#13 0x0000000000752210 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3)
    at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/Zend/zend.c:1327
#14 0x00000000006f3b52 in php_execute_script (primary_file=primary_file@entry=0x7fffd1825b40)
    at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/main/main.c:2525
#15 0x000000000080358e in do_cli (argc=11, argv=0xf95df0) at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/sapi/cli/php_cli.c:994
#16 0x000000000047aca0 in main (argc=11, argv=0xf95df0) at /var/tmp/portage/dev-lang/php-5.5.24/work/sapis-build/cli/sapi/cli/php_cli.c:1378
(gdb) 
```

**Comment by davidpersson** [comment]
This is probably not related to lcms. I've had imagemagick compiled with ghostscript support and ghostscript in version 9.10 installed. Updating gs to 9.15 fixed the problem for me. 

Feel free to close this ticket, I wasn't sure if the backtrace might contain valuable information.

Thanks for lcms - I use it everyday :)

**Comment by mm2** [comment]
As you say, this is not on lcms side, so I'm closing the issue.
Thanks
